# Generated by Django 2.1.8 on 2019-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('titleid', models.CharField(max_length=264)),
                ('rating', models.FloatField()),
                ('cast', models.CharField(max_length=264)),
            ],
        ),
    ]
